spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forumalura
    username: sa
    password: 1wi46sS@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null