spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/forumalura
    username: sa
    password: 1wi46sS@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: SuaChaveSuperSeguraDePeloMenos32Caracteres
