spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car
    username: sa
    password: 1wi46sS@
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379